### ISSUE TITLE
LocalDateTimePicker throws exception after calling `.getDatePickerI18n().setFirstDayOfWeek( 1 )`.

### ISSUE THREAD

**Issue by basil-bourque** [vaadin/platform#1335] opened 2020-05-12 01:08 UTC
When running Vaadin Flow 14.2.0.beta1, and trying to use the new `LocalDateTimePicker` tool, I tried setting the first day of the week to Monday. Doing so throws a mysterious exception when the app runs.

Apparently the problem may be that `dateTimePicker.getDatePickerI18n()` returns null by default. This makes no sense to me as attributes such as the first-day-of-week are already existing on the `DatePicker`/`LocalDateTimePicker`. I am trying to affect the default behavior already exhibited by the widget, to switch from the currently displayed Sunday as first day to the Monday as first day. 

Here is the complete little app to demo the problem.

    package work.basil.example;
    
    import com.vaadin.flow.component.Key;
    import com.vaadin.flow.component.button.Button;
    import com.vaadin.flow.component.button.ButtonVariant;
    import com.vaadin.flow.component.dependency.CssImport;
    import com.vaadin.flow.component.notification.Notification;
    import com.vaadin.flow.component.orderedlayout.VerticalLayout;
    import com.vaadin.flow.component.textfield.TextField;
    import com.vaadin.flow.router.Route;
    import com.vaadin.flow.server.PWA;
    
    import java.time.Duration;
    import java.time.LocalDateTime;
    import java.util.Locale;
    
    import com.vaadin.flow.component.datetimepicker.DateTimePicker;
    
    /**
     * The main view contains a button and a click listener.
     */
    @Route ( "" )
    @PWA ( name = "Project Base for Vaadin", shortName = "Project Base", enableInstallPrompt = false )
    @CssImport ( "./styles/shared-styles.css" )
    @CssImport ( value = "./styles/vaadin-text-field-styles.css", themeFor = "vaadin-text-field" )
    public class MainView extends VerticalLayout
    {
    
        public MainView ( )
        {
            DateTimePicker dateTimePicker = new DateTimePicker();
            dateTimePicker.setMin( LocalDateTime.now() );
            dateTimePicker.getDatePickerI18n().setFirstDayOfWeek( 1 );  // <-- Results in exception being thrown. Deleting this line prevents the exception.
    
            this.add( dateTimePicker );
        }
    }

When using web browser to load the web app, this is thrown:

    There was an exception while trying to navigate to '' with the exception message 'Unable to create an instance of 'work.basil.example.MainView'. The constructor threw an exception.'
    java.lang.IllegalArgumentException: Unable to create an instance of 'work.basil.example.MainView'. The constructor threw an exception.
    	at com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:512)
    	at com.vaadin.flow.internal.ReflectTools.createInstance(ReflectTools.java:449)
    	at com.vaadin.flow.di.DefaultInstantiator.create(DefaultInstantiator.java:137)
    	at com.vaadin.flow.di.DefaultInstantiator.getOrCreate(DefaultInstantiator.java:66)
    	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:160)
    	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:130)
    	at java.base/java.util.Optional.orElseGet(Optional.java:362)
    	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:129)
    	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:454)
    	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:433)
    	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:218)
    	at com.vaadin.flow.router.Router.handleNavigation(Router.java:223)
    	at com.vaadin.flow.router.Router.navigate(Router.java:194)
    	at com.vaadin.flow.router.Router.initializeUI(Router.java:92)
    	at com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1516)
    	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:472)
    	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
    	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545)
    	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
    	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:716)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
    	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:147)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1578)
    	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:536)
    	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
    	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:587)
    	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
    	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:228)
    	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1575)
    	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:226)
    	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1237)
    	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:181)
    	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:475)
    	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1548)
    	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:179)
    	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1156)
    	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:134)
    	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:218)
    	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
    	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
    	at org.eclipse.jetty.server.Server.handle(Server.java:545)
    	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:375)
    	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:559)
    	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:367)
    	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:290)
    	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:321)
    	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
    	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
    	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:823)
    	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:945)
    	at java.base/java.lang.Thread.run(Thread.java:832)
    Caused by: java.lang.reflect.InvocationTargetException
    	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
    	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
    	at com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:481)
    	... 51 more
    Caused by: java.lang.NullPointerException
    	at work.basil.example.MainView.<init>(MainView.java:33)
    	... 57 more

**Comment by Haprog** [comment] 2020-05-12 05:53
This is intended behaviour. For the first public version of the new `DateTimePicker` this has been implemented consistently in the same way as it already works with the older `DatePicker`. You can see the [DatePicker localization demo](https://vaadin.com/components/vaadin-date-picker/java-examples/localization) for how it is supposed to be used right now.

Basically you need to create a `new DatePickerI18n()` with all the properties and then use the setter.

I know it's not good developer experience especially when you only want to set one property. We have been talking about making this better so that the Java API would have default values populated (currently those default values are only known by the web component on client side and those are not synchronized to the server) and so that it would set the values in a different way to the client side since it's possible to override single values on client instead of overriding the whole i18n object.

Personally I don't know why it has been originally implemented this way in `DatePicker`.

We will need to make this API better for both `DatePicker` and `DateTimePicker` in the future.

There's also this related issue of being able to globally apply localization on app level instead of needing to set localization options for every component instance separately: https://github.com/vaadin/vaadin-core/issues/237

**Comment by Haprog** [comment] 2020-05-12 06:22
For your specific situation when you only want to set one of the i18n properties. Here's a simple workaround:

```java
dateTimePicker.getElement().executeJs("this.set('i18n.firstDayOfWeek', 1)");
```
(Note: this only seems to work before the date picker overlay has been opened for the first time, so you can't dynamically change the first day of week after that.)

**Comment by Haprog** [comment] 2020-05-12 06:30
This issue is also slightly related https://github.com/vaadin/vaadin-date-picker-flow/issues/49

**Comment by vaadin-miki** [comment] 2020-05-12 08:09
This issue should be rephrased into "make i18n not null when the component is created", which is basically the same as the issue @Haprog linked. It is confusing, especially for a Java developer, to see the object's properties on the client-side and at the same time an NPE in Java.

**Comment by Haprog** [comment] 2020-05-12 08:44
Here's a new issue for tracking the I18N Java API enhancements across several components: https://github.com/vaadin/vaadin/issues/68

Closing this issue in favor of that one.

**Closed by Haprog** 2020-05-12 08:44 UTC
