### ISSUE TITLE
Material dark theme variant in View not picked up in 14beta2

### ISSUE THREAD

**Issue by eiswind** [vaadin/platform#679] opened 2019-05-27 11:37 UTC
```
@Route
@Theme(value = Material::class, variant = Material.DARK)
class LoginView(
```
is not rendered with the dark variant, whereas it works on other views with a layout

```
@Theme(value = Material::class, variant = Material.DARK)
class MainLayout : AppLayout(), RouterLayout, BeforeEnterObserver {
```

I noticed that its rendered dark as soon as a buttonclick happened on the page.

**Comment by pleku** [comment] 2019-05-27 11:58
Thanks for the report!

This is a duplicate of https://github.com/vaadin/flow/issues/5715 and has already been fixed, to be released in the next 14 version.

**Comment by pleku** [comment] 2019-05-27 12:04
Oops, actually I think this is not related to the ^ issue. Reopening and moving to vaadin/flow repository

**Comment by pleku** [comment] 2019-05-27 12:20
Moved to vaadin/flow#5781

**Closed by pleku** 2019-05-27 12:20 UTC
