### ISSUE TITLE
Combobox has diffrent behavior in horizontallayout and tab 

### ISSUE THREAD

**Issue by maxiking445** [vaadin/platform#987] opened 2019-11-14 14:49 UTC
just came upon this issue while trying to type space into the combobox.  It seems like the tab component overwrites the "_keyup_"/"_keydown_" event of the combobox. 
So you are only able to type in some spaces if the horizontal layout is set as parent. 

```
@Route("test")
public class View extends Div {

    public View (){
        Tab tab = new Tab(); // Make this horizontal and it will work
        ComboBox<String> combo = new ComboBox<>();
        tab.add(combo);
        this.add(tab);
    }


}
```
Is this behavior of the tab component wanted ? 

Vaadin Version is 14.0.12 

Greetings 
Max

**Comment by web-padawan** [comment] 2019-11-14 14:54
Tab component is not expected to contain any field components such as combo-box. This will affect focus, keydown events etc.

So I think the behavior is as expected.

**Comment by web-padawan** [comment] 2019-11-15 09:48
Closing per above comment as working as intended.

**Closed by web-padawan** 2019-11-15 09:48 UTC
