### ISSUE TITLE
24.5.1 doesn't start with a Hilla/React Parent Layout

### ISSUE THREAD

**Issue by SebastianKuehnau** [vaadin/platform#6919] opened 2024-10-24 10:08 UTC
### Describe the bug

I have a Vaadin app with view implemented in Flow with a Parent Layout in React and Automatic Layouts. Starting the application I'm getting the following error message:

```
com.vaadin.flow.server.InvalidRouteConfigurationException: Invalid route configuration. The following Hilla route(s) conflict with configured Flow routes: 
	at com.vaadin.flow.router.internal.RouteUtil.checkForClientRouteCollisions(RouteUtil.java:653) ~[flow-server-24.5.1.jar:24.5.1]
	at com.vaadin.flow.router.internal.RouteUtil.checkForClientRouteCollisions(RouteUtil.java:613) ~[flow-server-24.5.1.jar:24.5.1]
```

### Expected-behavior

application starts like in 24.5.0

### Reproduction

go to start.vaadin.com, add flow view to your app and a main layout implemented in hilla.

try to start the app with vaadin 24.5.1

### System Info

MacOS 15.0.1
Java jbr_jcef-21.0.4-osx-aarch64-b620.4
Chrome 130
IntelliJ 2024.2.4 (Ultimate Edition)

**Comment by Artur-** [comment] 2024-10-24 10:15
Can't reproduce. The app starts fine with `@layout.tsx` and 
```java
@Route("")
public class EmptyView extends VerticalLayout {
```

**Comment by Artur-** [comment] 2024-10-24 10:16
Scrap that, the project was still using 24.5.0 where it works. 24.5.1 is indeed broken

**Comment by SebastianKuehnau** [comment] 2024-10-24 10:17
with 24.5.1 the debugger is running through RouteUtil.checkForClientRouteCollisions, which has not happened in 24.5.0.

**Comment by Artur-** [comment] 2024-10-24 10:24
Likely fixed by https://github.com/vaadin/flow/pull/20327

**Comment by Artur-** [comment] 2024-10-28 09:36
Works with 24.5.2

**Closed by Artur-** 2024-10-28 09:36 UTC
Labels: bug
