### ISSUE TITLE
Multi-Select ComboBox: List keeps empty in read only mode

### ISSUE THREAD

**Issue by fabst2w** [vaadin/platform#3257] opened 2022-09-10 16:43 UTC
### Describe the bug

The list of Multi-Select ComboBox is blank when in read-only mode.
![image](https://user-images.githubusercontent.com/59484106/189493143-4175393f-d648-4c28-90a4-c062121aa522.png)

### Expected-behavior

It should show the selected values. Especially those that are hidden within the chip number.

### Reproduction

Go to https://vaadin.com/docs/latest/components/multi-select-combo-box/#read-only
Open that Combobox.

### System Info

Ubuntu 22.04, Chromium 105, Vaadin 23.2

**Comment by tomivirkki** [comment] 2022-09-10 19:59
Seems to be a duplicate of https://github.com/vaadin/flow-components/issues/3684

**Comment by web-padawan** [comment] 2022-09-10 20:38
Closing in favor of https://github.com/vaadin/flow-components/issues/3684 per above comment.

**Closed by web-padawan** 2022-09-10 20:38 UTC
Labels: bug
